### ISSUE TITLE
Manager deletes placement metadata on docker-compose stop

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/membership-manager#4]
A start/stop sequence in docker-compose will end up leaving pg_dist_shard/pg_dist_partition metadata, but it deletes pg_dist_placement. Thus if I create a table, load data, and then call a `stop` on my cluster, I essentially lose all placement metadata. 

Also, https://github.com/citusdata/membership-manager/blob/master/manager.py#L31 deletes from pg_dist_shard_placement instead of pg_dist_placement. We have deprecated pg_dist_shard_placement, and so this should be updated.

Docker logs for citus_manager shows:
```
listening for events...
adding citus_worker_4
adding citus_worker_2
adding citus_worker_3
adding citus_worker_1
removing citus_worker_4
removing citus_worker_2
removing citus_worker_3
removing citus_worker_1
shutting down...
```

Also, is removing the placement metadata really the best approach in case of a 'die'?

**Comment by colton-citus** [comment]
Do we have a good reason to call remove_worker on die? I'd think that it would be more suitable to call remove_worker on destroy instead.

**Comment by jasonmp85** [comment]
> Do we have a good reason to call remove_worker on die? I'd think that it would be more suitable to call remove_worker on destroy instead.

Agreed.

**Comment by colton-citus** [comment]
Created PR https://github.com/citusdata/membership-manager/pull/5 to address this.

**Comment by shashankkr9** [comment]
Any update on this. Facing the same issue. Looks like the PR is pending to be merged for quite some time.

**Comment by waiyan1612** [comment]
Is there any ETA on when this will be merged to master? We are evaluating Citus and this is a blocker for us to move forward.

**Comment by shashankkr9** [comment]
@sumedhpathak @colton-citus any update on this.

**Comment by jan-zajic** [comment]
@onurctirtir, @jasonmp85 can anyone from Citus take care of this?

**Comment by SaitTalhaNisanci** [comment]
As a reference to when which event is triggered:

![image](https://user-images.githubusercontent.com/17179875/73068491-6fe0d200-3ebc-11ea-8f67-e6cf7ca3d265.png)

**Comment by mhaagens** [comment]
Seems Citus doesn't care about Docker usage?

**Comment by ghost** [comment]
@mhaagens We just opened up two PRs working to address this - we would appreciate your help testing them in your environment and making sure they fix the issue:

https://github.com/citusdata/membership-manager/pull/7
https://github.com/citusdata/membership-manager/pull/8
